### ISSUE TITLE
Tracking Calendar (Low Priority)

### ISSUE THREAD

**Issue by BrandonKMLee** [thomasmarkiewicz/bodysculpting#21]
https://github.com/Yuncun/AbusiveGymReminder

- [ ] Mark down done gym days
- [ ] Color days based on success vs failed sets vs missing gym
- [ ] Progression graph of activity (rather than weight like in the 5x5 app)
